# docker-compose.yml
version: '3.8'

services:
  goalservice:
    image: goal-service:latest 
    ports:
      - "3009:3009"  # Map host port 3009 to container port 3009
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root12345
      - DATABASE_NAME=progress_tracker_db
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_DATABASE=progress_tracker_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
