# docker-compose.yml
version: '3.8'

services:
  goalservice:
    image: goal-service:latest 
    ports:
      - "3009:3009"  # Map host port 3009 to container port 3009
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=YOUR_DB_PORT
      - DATABASE_USER=YOUR_USER
      - DATABASE_PASSWORD=YOUR_PASSWORD
      - DATABASE_NAME=YOUR_DB_NAME
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
      - MYSQL_DATABASE=YOUR_DB_NAME
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
