# goal-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goal-service
  template:
    metadata:
      labels:
        app: goal-service
    spec:
      containers:
        - name: goal-service
          image: zaidalogaili/goal-service:latest
          env:
            - name: DATABASE_URL
              value: "YOUR_DATABASE_URL"
            