# docker-compose.yml

version: '3.8'

services:
  userservice:
    image: user-service:latest  # Change this line to use the local image
    ports:
      - "3008:3008"  # Map host port 3008 to container port 3008
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root12345
      - DATABASE_NAME=progress_tracker_user_db
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:latest
    ports:
      - "3304:3306"  # This should be 3306 for MySQL, not 3304
    environment:
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_DATABASE=progress_tracker_user_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
